export default {
    SELECT_TRIP_NAME: 'SELECT_TRIP_NAME',
    SELECT_DESTINATION: 'SELECT_DESTINATION',
    REQUEST_SUGGESTION_DESTINATION: 'REQUEST_SUGGESTION_DESTINATION',
    RECEIVE_SUGGESTION_DESTINATION: 'RECEIVE_SUGGESTION_DESTINATION',
    REQUEST_DESTINATION: 'REQUEST_DESTINATION',
    RECEIVE_DESTINATION: 'RECEIVE_DESTINATION',
}